
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app_1
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - PORT=${PORT_1}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${INSTANCE_1}
      - SPRING_DATASOURCE_USERNAME=${INSTANCE_1}
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db_1
    environment:
      - POSTGRES_USER=${INSTANCE_1}
      - POSTGRES_PASSWORD=password